/**  ******************************************************************************  * @file    atmega644p_gpio.c  * @author  Basavaraju B V  * @version V1.0.0  * @date    09-July-2013  * @brief   This file contails basic functions to initialize the GPIOs in the controller  * @Note	 If the mode is selected as input, then for the corresponding pin  *			 resistor should be pulled-up by writing 1 to that pin.  ******************************************************************************  *  *					HOW TO USE  * 1. Call the appropiate function with the arguents which whose enums are in the atmega644p_gpio.h file.  ******************************************************************************  *//* Includes ------------------------------------------------------------------*/
#include "atmega644p_gpio.h"
/*
 *  This Function returns the pointer to the SFR_IO8 page! So it should be volatile
 *  Check iomxx4.h file for more detials on PORTx/PINx/DDRx
 *  Check the file sfr_defs.h for more details on SFR Pages and address!
 *  As the atmega644p is a 8 bit controller the return address is of type uint8_t
 *  Volatile is used for ret value and the function because to avoid warnings and compiler should not optimise the code!
 */static volatile uint8_t *(GetSFR_IO_Reg(ports GPIOx, actions action)){
    volatile uint8_t *ret = 0;    switch(GPIOx+action)	{		case 0:		ret = &(PINA); 	    break;		case 1:		ret = &(DDRA); 	    break;		case 2:		ret = &(PORTA); 	break;		case 3:		ret = &(PINB); 	    break;		case 4:		ret = &(DDRB); 	    break;		case 5:		ret = &(PORTB); 	break;		case 6:		ret = &(PINC); 	    break;		case 7:		ret = &(DDRC); 	    break;		case 8:		ret = &(PORTC); 	break;		case 9:		ret = &(PIND); 	    break;		case 10:	ret = &(DDRD); 	    break;		case 11:	ret = &(PORTD); 	break;		//defaulf: 			            break;	}
	return ret;}void GPIO_Write(ports GPIOx, pins pin, uint8_t val){	volatile uint8_t *GPIO = GetSFR_IO_Reg(GPIOx, WRITE);	if(val != GPIO_PIN_RESET)	{		*GPIO = (*GPIO | pin);	}	else	{		*GPIO = (*GPIO & ~pin);	}}uint8_t GPIO_Read(ports GPIOx, pins pin){	volatile uint8_t *GPIO = GetSFR_IO_Reg(GPIOx, READ);	return (*GPIO & pin);}void GPIO_Config(ports GPIOx, pins pin, modes mode){	volatile uint8_t *GPIO = GetSFR_IO_Reg(GPIOx, CONFIG);	if(mode != INPUT)	{		*GPIO = (*GPIO | pin);	}	else	{		*GPIO = (*GPIO & ~pin);		/*		*	once the Pin is configured as input. Internal PULL-UP resister		*	should be activated. Below code does that.		*/		GPIO = GetSFR_IO_Reg(GPIOx, WRITE);		*GPIO = (*GPIO | pin);	}}

